language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/rakudo-nostar

script: docker run --entrypoint sh -t -v  $TRAVIS_BUILD_DIR:/home/raku jjmerelo/rakudo-nostar  -c "zef install --deps-only . && zef build . && zef test ."
