language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6  -c "apk add --update --no-cache make build-base gcc && zef install --deps-only . && zef build . && zef test ."
